function func_show_eeg_events(app, EEG)

    % Create table
    n_events = length(EEG.event);

    tab_pop = table( ...
        (1:n_events)', ...
        extractfield(EEG.event,'type')', ...
        extractfield(EEG.event,'begintime')', ...
        (extractfield(EEG.event,'latency') / EEG.srate)', ...
        'VariableNames', {'Index','Type','BeginTime','Latency_sec'} ...
    );

    % Create popup
    fig = uifigure( ...
        'Name', 'EEG Events', ...
        'Position', [100 100 760 500] ...
    );

    % Title text
    uilabel(fig, ...
        'Text', sprintf('EEG Events: %d total events', n_events), ...
        'Position', [20 455 720 30], ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 16, ...
        'FontWeight', 'bold');

    % Create uitable
    uitable(fig, ...
        'Data', tab_pop, ...
        'Position', [20 70 720 370]);

    % Close button
    uibutton(fig, ...
        'Text', 'Close', ...
        'Position', [330 20 100 30], ...
        'ButtonPushedFcn', @(btn,event) close(fig));

end